### ISSUE TITLE
MemoryError when installing latest lambda-packages

### ISSUE THREAD

**Issue by robertdfrench** [Miserlou/lambda-packages#27]
Is anyone else running in to this?

I am trying to install lambda-packages with pip 9.0.1 in a py2.7.12 virtualenv on amazon linux and getting a MemoryError. This is a small box with half a gig of ram, but I am not running any other processes. If no one else is seeing this, I will just chalk it up to cheap hardware.

```
(.venv)[ec2-user@ec2-dev-box dope-ass-lambda-app]$ pip install lambda-packages
Collecting lambda-packages
  Downloading lambda_packages-0.10.0-py2-none-any.whl (56.1MB)
    99% |############################### | 56.1MB 50.1MB/s eta 0:00:01Exception:
Traceback (most recent call last):
  File "/home/ec2-user/dope-ass-lambda-app/.venv/local/lib/python2.7/site-packages/pip/basecommand.py", line 215, in main
    status = self.run(options, args)
  File "/home/ec2-user/dope-ass-lambda-app/.venv/local/lib/python2.7/site-packages/pip/commands/install.py", line 324, in run
    requirement_set.prepare_files(finder)
  File "/home/ec2-user/dope-ass-lambda-app/.venv/local/lib/python2.7/site-packages/pip/req/req_set.py", line 380, in prepare_files
    ignore_dependencies=self.ignore_dependencies))
  File "/home/ec2-user/dope-ass-lambda-app/.venv/local/lib/python2.7/site-packages/pip/req/req_set.py", line 620, in _prepare_file
    session=self.session, hashes=hashes)
  File "/home/ec2-user/dope-ass-lambda-app/.venv/local/lib/python2.7/site-packages/pip/download.py", line 821, in unpack_url
    hashes=hashes
  File "/home/ec2-user/dope-ass-lambda-app/.venv/local/lib/python2.7/site-packages/pip/download.py", line 659, in unpack_http_url
    hashes)
  File "/home/ec2-user/dope-ass-lambda-app/.venv/local/lib/python2.7/site-packages/pip/download.py", line 882, in _download_http_url
    _download_url(resp, link, content_file, hashes)
  File "/home/ec2-user/dope-ass-lambda-app/.venv/local/lib/python2.7/site-packages/pip/download.py", line 603, in _download_url
    hashes.check_against_chunks(downloaded_chunks)
  File "/home/ec2-user/dope-ass-lambda-app/.venv/local/lib/python2.7/site-packages/pip/utils/hashes.py", line 46, in check_against_chunks
    for chunk in chunks:
  File "/home/ec2-user/dope-ass-lambda-app/.venv/local/lib/python2.7/site-packages/pip/download.py", line 571, in written_chunks
    for chunk in chunks:
  File "/home/ec2-user/dope-ass-lambda-app/.venv/local/lib/python2.7/site-packages/pip/utils/ui.py", line 139, in iter
    for x in it:
  File "/home/ec2-user/dope-ass-lambda-app/.venv/local/lib/python2.7/site-packages/pip/download.py", line 560, in resp_read
    decode_content=False):
  File "/home/ec2-user/dope-ass-lambda-app/.venv/local/lib/python2.7/site-packages/pip/_vendor/requests/packages/urllib3/response.py", line 357, in stream
    data = self.read(amt=amt, decode_content=decode_content)
  File "/home/ec2-user/dope-ass-lambda-app/.venv/local/lib/python2.7/site-packages/pip/_vendor/requests/packages/urllib3/response.py", line 314, in read
    data = self._fp.read(amt)
  File "/home/ec2-user/dope-ass-lambda-app/.venv/local/lib/python2.7/site-packages/pip/_vendor/cachecontrol/filewrapper.py", line 63, in read
    self._close()
  File "/home/ec2-user/dope-ass-lambda-app/.venv/local/lib/python2.7/site-packages/pip/_vendor/cachecontrol/filewrapper.py", line 50, in _close
    self.__callback(self.__buf.getvalue())
  File "/home/ec2-user/dope-ass-lambda-app/.venv/local/lib/python2.7/site-packages/pip/_vendor/cachecontrol/controller.py", line 275, in cache_response
    self.serializer.dumps(request, response, body=body),
  File "/home/ec2-user/dope-ass-lambda-app/.venv/local/lib/python2.7/site-packages/pip/_vendor/cachecontrol/serialize.py", line 55, in dumps
    "body": _b64_encode_bytes(body),
  File "/home/ec2-user/dope-ass-lambda-app/.venv/local/lib/python2.7/site-packages/pip/_vendor/cachecontrol/serialize.py", line 12, in _b64_encode_bytes
    return base64.b64encode(b).decode("ascii")
MemoryError
```

**Comment by Miserlou** [comment]
That sounds like it might be a bug in pip, maybe report upstream?

From my phone..

**Comment by robertdfrench** [comment]
Yup! It looks related to https://github.com/pypa/pip/issues/2984, and the workaround suggested by those folks also worked for me. Thanks @Miserlou

**Comment by Miserlou** [comment]
Thanks for reporting that, @robertdfrench. For those who stumble upon this error, the work-around referenced is to use `pip install --no-cache-dir lambda-packages`
