### ISSUE TITLE
Using mysqldb with lambda and zappa

### ISSUE THREAD

**Issue by stevezau** [Miserlou/lambda-packages#38]
Hi,

Following to instructions, simple installing this package, or letting zappa install it does not seem to give me mysqldb within my lambda function. I get 

[1489527885652] ImportError: No module named MySQLdb

Am i missing something here? I also checked the package zip and it's not in there either. I am running mac though, do i need to run package on an aws machine?

**Comment by Miserlou** [comment]
Are you in a venv?

**Comment by stevezau** [comment]
Yep in a venv on a mac using pycharm.

**Comment by senseysensor** [comment]
+1. After deploying with zappa `import MySQLdb` results in `ImportError` _No module named MySQLdb_

**Comment by perwagner** [comment]
I'm using Python 3.6 and have the same problem.

**Comment by bonoyi87** [comment]
I'm also using Python 3.6 and have the same problem !!

**Comment by rafaelhenrique** [comment]
Same here.

**Comment by FlipperPA** [comment]
Silly question, but are you using `MySQLdb` or `mysqlclient`? If you're using a venv against the system Python on a Mac, you're using Python 2, instead of Python 3.6. `mysqlclient` is supposed to be a "drop-in" replacement for `MySQLdb`, but with Python 3 compatibility:

https://docs.djangoproject.com/en/1.11/ref/databases/#mysql-db-api-drivers

`MySQLdb` only supports Python 2, and support for it is being dropped in Django 2.0.

**Comment by rafaelhenrique** [comment]
Hi @FlipperPA !

I tried to use mysqlclient (with Python3), but many incompatibilities happen, the instance "image" provisioned in lambda does not have libmariaXXX.so (Maria DB / MysqlDB libraries). 

But MySQLdb with Python 2 works fine.

**Comment by mjscalexander** [comment]
I am having this same error.
Error loading MySQLdb module: No module named 'MySQLdb': ImproperlyConfigured
Traceback (most recent call last):
File "/var/task/process.py", line 169, in main
process(record, context)
File "/var/task/process.py", line 133, in process
django.setup()
File "/var/task/django/__init__.py", line 27, in setup
apps.populate(settings.INSTALLED_APPS)
File "/var/task/django/apps/registry.py", line 108, in populate
app_config.import_models(all_models)
File "/var/task/django/apps/config.py", line 199, in import_models
self.models_module = import_module(models_module_name)
File "/var/lang/lib/python3.6/importlib/__init__.py", line 126, in import_module
return _bootstrap._gcd_import(name[level:], package, level)
File "<frozen importlib._bootstrap>", line 994, in _gcd_import
File "<frozen importlib._bootstrap>", line 971, in _find_and_load
File "<frozen importlib._bootstrap>", line 955, in _find_and_load_unlocked
File "<frozen importlib._bootstrap>", line 665, in _load_unlocked
File "<frozen importlib._bootstrap_external>", line 678, in exec_module
File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
File "/var/task/django/contrib/auth/models.py", line 4, in <module>
from django.contrib.auth.base_user import AbstractBaseUser, BaseUserManager
File "/var/task/django/contrib/auth/base_user.py", line 52, in <module>
class AbstractBaseUser(models.Model):
File "/var/task/django/db/models/base.py", line 119, in __new__
new_class.add_to_class('_meta', Options(meta, app_label))
File "/var/task/django/db/models/base.py", line 316, in add_to_class
value.contribute_to_class(cls, name)
File "/var/task/django/db/models/options.py", line 214, in contribute_to_class
self.db_table = truncate_name(self.db_table, connection.ops.max_name_length())
File "/var/task/django/db/__init__.py", line 33, in __getattr__
return getattr(connections[DEFAULT_DB_ALIAS], item)
File "/var/task/django/db/utils.py", line 211, in __getitem__
backend = load_backend(db['ENGINE'])
File "/var/task/django/db/utils.py", line 115, in load_backend
return import_module('%s.base' % backend_name)
File "/var/lang/lib/python3.6/importlib/__init__.py", line 126, in import_module
return _bootstrap._gcd_import(name[level:], package, level)
File "/var/task/django/db/backends/mysql/base.py", line 28, in <module>
raise ImproperlyConfigured("Error loading MySQLdb module: %s" % e)
django.core.exceptions.ImproperlyConfigured: Error loading MySQLdb module: No module named 'MySQLdb'
