### ISSUE TITLE
Installation Fail...

### ISSUE THREAD

**Issue by Chanonry** [Miserlou/lambda-packages#57]
Downloading ok but failing to install ?? Thoughts ?

Which version of openCV was compiled?

A

MacBook-Air:lambda-packages andyspence$ pip install lambda-packages -t ~/lambda-packages
Collecting lambda-packages
  Downloading lambda_packages-0.16.1.tar.gz (59.2MB)
    100% |████████████████████████████████| 59.2MB 10kB/s 
Building wheels for collected packages: lambda-packages
  Running setup.py bdist_wheel for lambda-packages ... done
  Stored in directory: /Users/andyspence/Library/Caches/pip/wheels/4e/64/d1/8040cf0b70654f663de66405e814cae219d4ac0542d75deb53
Successfully built lambda-packages
Installing collected packages: lambda-packages
Exception:
Traceback (most recent call last):
  File "/usr/local/lib/python2.7/site-packages/pip/basecommand.py", line 215, in main
    status = self.run(options, args)
  File "/usr/local/lib/python2.7/site-packages/pip/commands/install.py", line 342, in run
    prefix=options.prefix_path,
  File "/usr/local/lib/python2.7/site-packages/pip/req/req_set.py", line 784, in install
    **kwargs
  File "/usr/local/lib/python2.7/site-packages/pip/req/req_install.py", line 851, in install
    self.move_wheel_files(self.source_dir, root=root, prefix=prefix)
  File "/usr/local/lib/python2.7/site-packages/pip/req/req_install.py", line 1064, in move_wheel_files
    isolated=self.isolated,
  File "/usr/local/lib/python2.7/site-packages/pip/wheel.py", line 247, in move_wheel_files
    prefix=prefix,
  File "/usr/local/lib/python2.7/site-packages/pip/locations.py", line 153, in distutils_scheme
    i.finalize_options()
  File "/usr/local/lib/python2.7/site-packages/setuptools/command/install.py", line 38, in finalize_options
    orig.install.finalize_options(self)
  File "/usr/local/Cellar/python/2.7.13/Frameworks/Python.framework/Versions/2.7/lib/python2.7/distutils/command/install.py", line 264, in finalize_options
    "must supply either home or prefix/exec-prefix -- not both"
DistutilsOptionError: must supply either home or prefix/exec-prefix -- not both

**Comment by Chanonry** [comment]
Sorted - I did it the 'wrong' way
